/*
Errors that can arise in the process of interpreting a Hulk expression.
*/
namespace Hulk;

/*
Base class for all Hulk defined exceptions.
*/
abstract class HulkException : Exception{
    abstract public string ErrorType();//Stablish the type of this error : Lexical, Syntactic, Semantic
    abstract public void HandleException();

    protected HulkException(string? message=""):base(message){}//Initailizes exception class with a message
}

/*
This kind of exception rise while scanning the source code. They represent
Hulk lexical errors.
*/
class ScannerException : HulkException{
    //The text of the line where the error happened.
    public string Contexto {get;}
    //Amount of characters from the begining of the line where the error happened. Its an aproximation of the error ubication.
    public int Ofsset {get;}

    public ScannerException():base(){
        this.Contexto = "";
        this.Ofsset = 0;
    }
    public ScannerException(string? message, string contexto, int offset):base(message){
        this.Contexto = contexto;
        this.Ofsset = offset;
    }

    public override string ErrorType(){
        return "LEXICAL ERROR";
    }
    public override void HandleException()
    {
        Hulk.Error(this);
        throw this;
    }
}

/*
This kind of exception rise while parsing the tokens produced by the scanner. They represent
Hulk syntactic errors.
*/
class ParserException : HulkException{
    public ParserException(string message) : base(message){}

    public override string ErrorType(){
        return "SYNTACTIC ERROR";
    }
    public override void HandleException()
    {
        Hulk.Error(this);
        throw this;
    }
}

/*
This kind of exceptions rise while interpreting the syntax tree generated by the parser. They represent
Hulk semantic errors.
Este tipo de excepciones ocurren al interpretar las expresiones parseadas y representan los errores
semnticos de Hulk.
*/
class InterpreterException : HulkException{
    public InterpreterException(string message) : base(message){}

    public override string ErrorType(){
        return "SEMANTIC ERROR";
    }
    public override void HandleException()
    {
        Hulk.Error(this);
        throw this;
    }
}